export const SeriesActionsTypes = {
  ADD_TYPE: 'ADD_TYPE',
  DATA_ANIME_SUCCESS: 'DATA_ANIME_SUCCESS',
  DATA_ANIME_STARTED: 'DATA_ANIME_STARTED',
  DATA_ANIME_FAILURE: 'DATA_ANIME_FAILURE',
  DATA_MANGA_SUCCESS: 'DATA_MANGA_SUCCESS',
  DATA_MANGA_STARTED: 'DATA_MANGA_STARTED',
  DATA_MANGA_FAILURE: 'DATA_MANGA_FAILURE',
};
